# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  test:
    docker:
      - image: circleci/elixir:1.11.2
    steps:
      - run:
        name: Run tests
        command: mix do compile --warnings-as-errors, coveralls.json

      - codecov/upload:
        file: "./coveralls.json"
        token: "f0ab5451-efeb-4c8a-8f45-5f699c9db5ce"
