# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2

- run:
  name: Run tests
  command: mix do compile --warnings-as-errors, coveralls.json

- codecov/upload:
  file: "./coveralls.json"
  token: a7a5df63-codcov-token-4278vh38
